name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      # Clean Workspace
      - run: rm -rf dist && rm -rf src/tokens
      # Install dependencies
      - run: npm install
      # Transform tokens into SD readable tokens
      - run: npx token-transformer src/tokens.json src/tokens/core.json
      # Run Style Dictionary Build
      - run: node build.js
      # Add files that were created during a run, e.g. created files from style dictionary or token-transformer.
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Tokens
